"""Initial_migration

Revision ID: 81ef1261ce94
Revises: 
Create Date: 2026-05-04 14:27:59.632933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ef1261ce94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True, comment='Weight in kilograms'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Height in centimeters'),
    sa.Column('pulse', sa.Integer(), nullable=True, comment='Resting heart rate in bpm'),
    sa.Column('calories_burned', sa.Float(), nullable=True, comment='Total calories burned'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometrics_id'), 'biometrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biometrics_id'), table_name='biometrics')
    op.drop_table('biometrics')
    # ### end Alembic commands ###
